### ISSUE TITLE
File list is totally vertical if the list doesn't fit into one line unless run with `-a`

### ISSUE THREAD

**Issue by Un1q32** [lsd-rs/lsd#1014] opened 2024-03-22 21:32 UTC
- os: macOS 14.4
- `lsd --version`: lsd 1.0.0 (it's the 1.1.0 binary, see #1012)
- `echo $TERM`: xterm-kitty
- `echo $LS_COLORS`: (none)

## Expected behavior

Wrapping behavior should be the same as 1.0.0, or the same as when run with `-a`

## Actual behavior
<img width="1280" alt="Screenshot 2024-03-22 at 5 29 28 PM" src="https://github.com/lsd-rs/lsd/assets/57970114/09763c84-f28c-4957-9175-ecfd634e6f70">

Zooming in shows a normal run can also have this problem if one line isnt enough to fit

<img width="1280" alt="Screenshot 2024-03-22 at 5 30 40 PM" src="https://github.com/lsd-rs/lsd/assets/57970114/ec4edc64-266d-4b7d-a80f-112e60f98998">

**Comment by wwwjfy** [comment] 2024-03-23 09:49
It seems `-a` doesn't matter (much) here.
My observation is if non-`.` items cannot fit in one line, it'll show one item per line.

In the above case non-`.` items are not many, so even though with both it's wider than one line, it still behaves as expected.

I'm using iTerm2. This is new in the last release.

**Comment by nogweii** [comment] 2024-03-23 16:52
* `lsd --version`: lsd 1.1.1
* `echo $TERM`: xterm-kitty
* Arch Linux

Running into the same issue.

I've aliased ls to `/usr/bin/lsd --icon=auto --color=auto -F`, and indeed adding -a will make wrap files as expected.

**Comment by oneElectron** [comment] 2024-03-23 20:45
I am also having this issue.
- ```lsd --version```: lsd 1.1.1
- ```echo $TERM```: alacritty
- MacOS 14.4

**Comment by FischLu** [comment] 2024-03-23 23:09
I have the same issue

* `lsd --version`: lsd 1.1.1
* `echo $TERM`: xterm-256color
* MacOS 14.4

**Comment by nogweii** [comment] 2024-03-24 03:23
Hm, I think I've found the root cause - `term_grid` [doesn't ignore ANSI codes when calculating the width of each entry](https://github.com/ogham/rust-term-grid/issues/13). That could be tricky to solve...

**Comment by CarloCattano** [comment] 2024-03-24 17:15
came here looking for others having the same. 
lsd 1.1.1

ls returns a vertical list of files if the size cant hold them all in one line

**Comment by CarloCattano** [comment] 2024-03-24 17:18
it works with the -v flag for some reason
```bash
lsd -v
```

**Comment by zwpaper** [comment] 2024-03-25 16:15
I decided to rollback the term_grid dependency and we can later discuss which version or libs we should upgrade to.

https://github.com/lsd-rs/lsd/pull/1019, after this one is merged, I will release a v1.1.2 to do a quick fix.

sorry for the bothering, I was kinda busy recently, but this should not be an excuse

**Comment by zwpaper** [comment] 2024-03-25 16:35
as now https://github.com/lsd-rs/lsd/releases/tag/v1.1.2 released, this would be close
/close

**Closed by zwpaper** 2024-03-25 16:35 UTC
